name: Update Dynamic Status Card

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Roda a cada 4 horas

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 

      - name: Get latest commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=format:%s)" >> $GITHUB_OUTPUT

      - name: Get random quote
        id: quote
        run: |
          quote_json=$(curl -s "https://api.quotable.io/random?maxLength=70&tags=technology|wisdom")
          quote_content=$(echo $quote_json | jq -r .content)
          quote_author=$(echo $quote_json | jq -r .author)
          echo "content=$quote_content" >> $GITHUB_OUTPUT
          echo "author=$quote_author" >> $GITHUB_OUTPUT

      - name: Generate new dynamic card
        uses: Mokkiv/dynamic-card@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEADER: 'STATUS REPORT: DEVGREICK'
          LINE1: 'LAST ACTIVITY: ${{ steps.commit.outputs.message }}'
          LINE2: '"${{ steps.quote.outputs.content }}"'
          LINE3: '- ${{ steps.quote.outputs.author }}'
          OUT_FOLDER: '.'
          OUT_FILENAME: 'dynamic-card.svg'
