name: Update Dynamic Status Card

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Roda a cada 4 horas

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dynamic content
        id: dynamic_content
        run: |
          # Escapa caracteres especiais para o script Python
          COMMIT_MSG=$(git log -1 --pretty=format:%s | sed "s/'/\\\'/g" | sed 's/"/\\"/g')
          echo "commit_message=$COMMIT_MSG" >> $GITHUB_OUTPUT

          QUOTE_JSON=$(curl -s "https://api.quotable.io/random?maxLength=60&tags=technology|wisdom")
          QUOTE_CONTENT=$(echo $QUOTE_JSON | jq -r .content | sed "s/'/\\\'/g" | sed 's/"/\\"/g')
          QUOTE_AUTHOR=$(echo $QUOTE_JSON | jq -r .author | sed "s/'/\\\'/g" | sed 's/"/\\"/g')
          echo "quote_content=$QUOTE_CONTENT" >> $GITHUB_OUTPUT
          echo "quote_author=$QUOTE_AUTHOR" >> $GITHUB_OUTPUT

      - name: Update SVG with new content
        run: |
          # Usa Python (que já vem instalado) para substituir o texto no template de forma segura
          python -c "
          with open('card-template.svg', 'r') as f:
              svg_content = f.read()
          
          svg_content = svg_content.replace('%%COMMIT%%', '${{ steps.dynamic_content.outputs.commit_message }}')
          svg_content = svg_content.replace('%%QUOTE%%', '${{ steps.dynamic_content.outputs.quote_content }}')
          svg_content = svg_content.replace('%%AUTHOR%%', '- ${{ steps.dynamic_content.outputs.quote_author }}')

          with open('dynamic-card.svg', 'w') as f:
              f.write(svg_content)
          "
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update dynamic status card"
          file_pattern: "dynamic-card.svg"
